#! /bin/bash -e

ln_force=""

function usage() {
    echo "Usage: ./make-symlinks [--force] DIR [PROGS]"
    echo " eg: ./make-symlinks pandoc"
    echo " or: ./make-symlinks yesod-bin yesod"
}

function copy-symlink() {
    src="$1"
    dstname=$(basename "$src")
    dst="$HOME/.bin/$dstname"

    echo ""
    echo "from: $src"
    echo "to:   $dst"

    if [ "$ln_force" = "true" ]; then
        ln --force -s "$src" "$dst"
    else
        ln -s "$src" "$dst"
    fi
}

case $1 in
    -f|--force)
        ln_force="true";
        shift;;
esac

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

base="$PWD/$1/.cabal-sandbox/bin/"
shift

if ! [ -d "$base" ]; then
    echo "error: base path $base"
    echo "error: does not exist or is not a directory."
    exit 1
fi

echo "creating symbolic links:"

if [ $# -gt 0 ]; then
    while [ $# -gt 0 ]; do
        copy-symlink "$base/$1"
        shift
    done
else
    for srcname in "$base"/*; do
        copy-symlink "$srcname"
    done
fi
